# frozen_string_literal: true

# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  property :is_derived,
           predicate: ::RDF::URI.intern('https://nnp.wustl.edu/terms/isDerived'),
           multiple: false do |index|
             index.as :stored_searchable
           end
  include ::Hyrax::FileSetBehavior
end
