# frozen_string_literal: true

# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  property :is_derived,
           predicate: ::RDF::URI.intern('https://id.loc.gov/ontologies/bibframe.html#p_derivedFrom'),
           multiple: false do |index|
             index.as :stored_searchable
           end
  include ::Hyrax::FileSetBehavior
end
